# Generated by Django 3.0 on 2020-07-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='type',
        ),
        migrations.AddField(
            model_name='play',
            name='type',
            field=models.ManyToManyField(help_text='Select a type for this play', to='hello_world.Type'),
        ),
    ]
