# Generated by Django 3.0 on 2020-07-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0005_auto_20200701_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playinfo',
            name='age_category',
            field=models.CharField(choices=[{'Forbidden under 12', '12+'}, {'Forbidden under 14', '14+'}, {'18+', 'Forbidden under 18'}], default='U12', max_length=18),
        ),
    ]
