# Generated by Django 3.0 on 2020-07-02 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0007_author_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='buyer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
