# Generated by Django 3.0 on 2020-07-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0008_ticket_buyer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(help_text='Enter a brief review', max_length=1000)),
                ('reviewer_name', models.CharField(max_length=20)),
                ('play', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_world.Play')),
            ],
        ),
    ]
